PAGE 60, 132
TITLE PROG2-1 
STSEG SEGMENT 
    DB 32 DUP(?)
STSEG ENDS
;------------------
DTSEG SEGMENT
    DATA_IN DB 25H,12H,15H,1FH,2BH
    SUM DB ?
DTSEG ENDS
;-----------------
CDSEG SEGMENT 
MAIN PROC FAR
    ASSUME CS:CDSEG,DS:DTSEG,SS:STSEG
    MOV AX,DTSEG
    MOV DS,AX 
    
    MOV CX,05
    MOV BX,OFFSET DATA_IN
    MOV AL,0
AGAIN:  ADD AL,[BX]
        INC BX
        DEC CX
        JNZ AGAIN   
        
    MOV SUM,AL
    MOV AH,4CH
    INT 21H
MAIN ENDP
CDSEG ENDS
END MAIN